# Generated by Django 5.2.15 on 2026-06-30 00:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('under_review', 'under_review'), ('planned', 'planned'), ('in_progress', 'in_progress'), ('shipped', 'shipped'), ('closed', 'closed'), ('duplicate', 'duplicate')], db_index=True, default='open', max_length=16)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='feature_requests.featurerequestrecord')),
            ],
            options={
                'db_table': 'feature_request',
            },
        ),
        migrations.CreateModel(
            name='StatusChangeLogRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderated_status_changes', to=settings.AUTH_USER_MODEL)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='feature_requests.featurerequestrecord')),
            ],
            options={
                'db_table': 'feature_request_status_log',
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feature_requests.featurerequestrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feature_request_vote',
            },
        ),
        migrations.AddIndex(
            model_name='featurerequestrecord',
            index=models.Index(fields=['status', '-vote_count', '-created_at'], name='idx_fr_top'),
        ),
        migrations.AddIndex(
            model_name='featurerequestrecord',
            index=models.Index(fields=['-created_at'], name='idx_fr_new'),
        ),
        migrations.AddIndex(
            model_name='statuschangelogrecord',
            index=models.Index(fields=['feature_request', '-changed_at'], name='idx_scl_fr_time'),
        ),
        migrations.AddConstraint(
            model_name='voterecord',
            constraint=models.UniqueConstraint(fields=('feature_request', 'user'), name='uniq_vote_per_user_per_request'),
        ),
    ]
